---
title: "Châtaigniers Corse"
author: "Malo"
date: "2025-01-19"
output: html_document
---

```{r setup, include = FALSE}
library(ggplot2)
library(ggpubr)
library(ggsignif)
library(plotly)
library(cowplot)
library(plotly)
library(reshape2)
library(igraph)
library(ggraph)
library(networkD3)
library(RColorBrewer)
library(ggvenn)
library(ggVennDiagram)

library(tidyverse)
library(tibble)

library(vegan)
library(ade4)
library(lme4)
library(lmerTest)
library(lmtest)
library(nlme)
# library(MuMIn)
# options(na.action = "na.fail")
# library(DHARMa)
# library(betareg)
library(psych)
library(VIM)
library(emmeans)


library(readxl)
library(investr)
library(stats)
library(knitr)
library(kableExtra)
```
# Set up
```{r}
invent <- read.csv(file = "inventory5.csv", header = T, stringsAsFactors = T)

invent_unique <- invent %>%
  select(Taxon.fonge, Phylum) %>%
  distinct() %>%
  group_by(Taxon.fonge) %>%
  slice(1)

essence_presence <- invent %>%
  mutate(Identifiant.site = paste0("S", Identifiant.site)) %>%
  distinct(Essence, Taxon.fonge) %>%
  mutate(present = 1) %>%
  pivot_wider(names_from = Taxon.fonge, values_from = present, values_fill = list(present = 0))
essence_presence <- as.data.frame(essence_presence)

row.names(essence_presence) <- essence_presence$Essence
essence_presence$Essence <- NULL

colsums_all <- colSums(essence_presence == 1)
kf_all <- data.frame(species = colnames(essence_presence), all = colsums_all, row.names = NULL)


essence_presence <- essence_presence %>%
  rownames_to_column(var = "species")
#Pivot to long format 
ess_pres_long <- essence_presence %>%
  pivot_longer(cols = -species, names_to = "fungi", values_to = "presence")


#Essence_presence casta
casta_fungus <- invent %>%
  filter(Essence == "Castanea sativa") %>%
  distinct(Taxon.fonge)

casta_fungus$Taxon.fonge <- as.character(casta_fungus$Taxon.fonge)

casta_fung_names <- casta_fungus$Taxon.fonge
essence_presence_casta <- essence_presence[, colnames(essence_presence) %in% casta_fung_names]
essence_presence_casta$species <- essence_presence$species
rownames(essence_presence_casta) <- essence_presence_casta$species
essence_presence_casta$species <- NULL

```

# Figure 1 - Camemberts
```{r}
#####Setup####
phy_fam <- invent %>%
  select(Phylum, Famille) %>%
  distinct()

count_family <- invent %>%
  select(Phylum, Famille) %>%
  group_by(Famille) %>%
  summarize(count = n()) %>%
  left_join(phy_fam, by = "Famille") %>%
  arrange(desc(count)) %>%
  mutate(perc = round((count / sum(count)) * 100, 2))


perc_phylum_all <- invent %>%
  select(Phylum, Famille) %>%
  group_by(Phylum) %>%
  summarize(count = n()) %>%
  mutate(perc = round((count/sum(count)) * 100, 2))


perc_phylum_s7 <- invent_s7 %>%
  select(Phylum, Famille) %>%
  group_by(Phylum) %>%
  summarize(count = n()) %>%
  mutate(perc = round((count/sum(count)) * 100, 2))


perc_phylum_s14 <- invent_s14 %>%
  select(Phylum, Famille) %>%
  group_by(Phylum) %>%
  summarize(count = n()) %>%
  mutate(perc = round((count/sum(count)) * 100, 2))


perc_phylum_s15 <- invent_s15 %>%
  select(Phylum, Famille) %>%
  group_by(Phylum) %>%
  summarize(count = n()) %>%
  mutate(perc = round((count/sum(count)) * 100, 2))


thresh_basidio <- 3.5

count_family_basidio <- count_family %>%
  filter(Phylum == "Basidiomycète") 
count_family_basidio$Famille <- as.character(count_family_basidio$Famille)
count_family_basidio <- count_family_basidio %>%
  mutate(Famille = ifelse(perc < thresh_basidio, "Other Basidiomycetes", Famille)) 
  


thresh_asco <- 5
count_family_asco <- count_family %>%
  filter(Phylum == "Ascomycète")
count_family_asco$Famille <- as.character(count_family_asco$Famille)
count_family_asco <- count_family_asco %>%
  mutate(Famille = ifelse(perc < thresh_asco, "Other Ascomycetes", Famille))

count_family_mucoro <- count_family %>%
  filter(Phylum == "Mucoromycète")


count_family_asco_basidio <-count_family_basidio %>%
  rbind(count_family_asco) %>%
  rbind(count_family_mucoro)


count_for_plot <- data.frame(
  Famille = c("Russulaceae", "Thelephoraceae", "Hydnangiaceae", 
             "Other Basidiomycetes", "Dothydeomycetes", "Myxotrichaceae", 
             "Pyronemataceae", "Helotiales", "Other Ascomycetes", "Mucoromycetes"),
  count = c(119, 104, 23, 144, 
            49, 41, 33, 32, 51,
            4)
)

count_for_plot <- count_for_plot %>%
  mutate(perc = round((count/sum(count)) * 100, 2))

count_for_plot$Famille <- factor(count_for_plot$Famille, levels = rev(c("Russulaceae", "Thelephoraceae", "Hydnangiaceae",
                                                                        "Other Basidiomycetes", "Dothydeomycetes", "Myxotrichaceae",
                                                                        "Pyronemataceae", "Helotiales", "Other Ascomycetes", "Mucoromycetes"))
)


colors_camembert <- c(
  "Russulaceae" = "#008b90",       
  "Thelephoraceae" = "#00a0a5",    
  "Hydnangiaceae" = "#00b5bb",     
  "Other Basidiomycetes" = "#00cad0", 
  "Dothydeomycetes" = "#d43d31",  
  "Myxotrichaceae" = "#ff4b3e",  
  "Pyronemataceae" = "#ff8c42",  
  "Helotiales" = "#FFBC27",      
  "Other Ascomycetes" = "#ffd983ff",
  "Mucoromycetes" = "#6800d1ff"
)

#####All sites####
plot_fam_all <- ggplot(count_for_plot, aes(x = "", y = count, fill = Famille)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar("y", start = 0) +
  scale_fill_manual(values = colors_camembert) +
  theme_pubclean() +
  labs(fill = "Family") +
  theme(axis.text.x = element_blank(), axis.title.x = element_blank(), axis.title.y = element_blank())

plot_fam_all
#####Site 7####
count_phylum_s7 <- count_phylum_s7 %>%
  mutate(percentage = round((count / sum(count)) * 100,2))

plot_phy_7 <- ggplot(count_phylum_s7, aes(x="", y=count, fill=Phylum)) +
  ggtitle("Site 7") +
  theme_nothing() +
  geom_bar(stat="identity", width=1) +
  coord_polar("y", start=0) +
  #geom_text(aes(label = paste0(percentage, "%")), position = position_stack(vjust=0.5)) +
  labs(x = NULL, y = NULL, fill = NULL) +
  scale_fill_manual(values = c("Ascomycète" = "#f8766dff", 
                               "Basidiomycète" = "#00bfc4ff", 
                               "Mucoromycète" = "#6800d1ff"))

plot_phy_7

#####Site 14####
count_phylum_s14 <- count_phylum_s14 %>%
  mutate(percentage = round((count / sum(count)) * 100,2))


plot_phy_14 <- ggplot(count_phylum_s14, aes(x="", y=count, fill=Phylum)) +
  theme_nothing() +
  geom_bar(stat="identity", width=1) +
  coord_polar("y", start=0) +
  #geom_text(aes(label = paste0(percentage, "%")), position = position_stack(vjust=0.5)) +
  labs(x = NULL, y = NULL, fill = NULL) +
  scale_fill_manual(values = c("Ascomycète" = "#f8766dff", 
                               "Basidiomycète" = "#00bfc4ff", 
                               "Mucoromycète" = "#6800d1ff"))

plot_phy_14


#####Site 15####
count_phylum_s15 <- count_phylum_s15 %>%
  mutate(percentage = round((count / sum(count)) * 100,2))

plot_phy_15 <- ggplot(count_phylum_s15, aes(x="", y=count, fill=Phylum)) +
  theme_nothing() +
  geom_bar(stat="identity", width=1) +
  coord_polar("y", start=0) +
  #geom_text(aes(label = paste0(percentage, "%")), position = position_stack(vjust=0.5)) +
  labs(x = NULL, y = NULL, fill = NULL) +
  scale_fill_manual(values = c("Ascomycète" = "#f8766dff", 
                               "Basidiomycète" = "#00bfc4ff", 
                               "Mucoromycète" = "#6800d1ff"))

plot_phy_15



```

# Figure 2 - Kf
```{r}
#Kf: degrees of mycorrhiza species, according to appearances and to families / phylums
#####All species####

essence_presence_list <- list()
for (i in 1:10) {
  essence_presence_list[[paste0("essence_presence_", i)]] <- invent %>%
    mutate(Identifiant.site = paste0("S", Identifiant.site)) %>%
    group_by(Taxon.fonge) %>%
    filter(n() == i) %>%
    distinct(Essence, Taxon.fonge) %>%
    mutate(present = 1) %>%
    pivot_wider(names_from = Taxon.fonge, values_from = present, values_fill = list(present = 0)) %>%
    as.data.frame()
  
  row.names(essence_presence_list[[paste0("essence_presence_", i)]]) <- essence_presence_list[[paste0("essence_presence_", i)]]$Essence
  essence_presence_list[[paste0("essence_presence_", i)]]$Essence <- NULL
}

essence_presence_list[["essence_presence_11"]] <- invent %>%
  mutate(Identifiant.site = paste0("S", Identifiant.site)) %>%
  group_by(Taxon.fonge) %>%
  filter(n() >= 11) %>%
  distinct(Essence, Taxon.fonge) %>%
  mutate(present = 1) %>%
  pivot_wider(names_from = Taxon.fonge, values_from = present, values_fill = list(present = 0)) %>%
  as.data.frame()

row.names(essence_presence_list[["essence_presence_11"]]) <- essence_presence_list[["essence_presence_11"]]$Essence
essence_presence_list[["essence_presence_11"]]$Essence <- NULL


kf_list <- list()
for (i in 1:11) {
  # Get the essence_presence dataset
  essence_presence_data <- essence_presence_list[[paste0("essence_presence_", i)]]
  
  # Calculate colSums for the dataset
  colsums <- colSums(essence_presence_data == 1)
  
  # Create a data frame with the results
  kf_list[[paste0("kf_", i)]] <- data.frame(species = colnames(essence_presence_data), all = colsums, row.names = NULL)
}


kf_added_list <- list()
for (i in 1:11) {
  kf <- kf_list[[paste0("kf_", i)]]
    
  kf_added_list[[paste0("kf_added_", i)]] <- kf %>%
    group_by(all) %>%
    summarize(count = n())
  
  
}


kf_combined <- list()

# Loop through the 11 datasets
for (i in 1:11) {
  kf_added <- kf_added_list[[paste0("kf_added_", i)]]
  
  #add number of appearances
  kf_added$appearances <- i
  
  #put in list
  kf_combined[[i]] <- kf_added
}

#bind datasets 
final_kf_combined <- bind_rows(kf_combined)
final_kf_combined$all <- as.character(final_kf_combined$all)


#####Basidio####
invent_basidio <- invent %>%
  filter(Phylum == "Basidiomycète")

essence_presence_basidio_list <- list()

for (i in 1:10) {
  essence_presence_basidio_list[[paste0("essence_presence_", i)]] <- invent_basidio %>%
    mutate(Identifiant.site = paste0("S", Identifiant.site)) %>%
    group_by(Taxon.fonge) %>%
    filter(n() == i) %>%
    distinct(Essence, Taxon.fonge) %>%
    mutate(present = 1) %>%
    pivot_wider(names_from = Taxon.fonge, values_from = present, values_fill = list(present = 0)) %>%
    as.data.frame()
  
  row.names(essence_presence_basidio_list[[paste0("essence_presence_", i)]]) <- essence_presence_basidio_list[[paste0("essence_presence_", i)]]$Essence
  essence_presence_basidio_list[[paste0("essence_presence_", i)]]$Essence <- NULL
}

essence_presence_basidio_list[["essence_presence_11"]] <- invent_basidio %>%
  mutate(Identifiant.site = paste0("S", Identifiant.site)) %>%
  group_by(Taxon.fonge) %>%
  filter(n() >= 11) %>%
  distinct(Essence, Taxon.fonge) %>%
  mutate(present = 1) %>%
  pivot_wider(names_from = Taxon.fonge, values_from = present, values_fill = list(present = 0)) %>%
  as.data.frame()

row.names(essence_presence_basidio_list[["essence_presence_11"]]) <- essence_presence_basidio_list[["essence_presence_11"]]$Essence
essence_presence_basidio_list[["essence_presence_11"]]$Essence <- NULL




kf_basidio_list <- list()
for (i in 1:11) {
  # Get the essence_presence dataset
  essence_presence_data <- essence_presence_basidio_list[[paste0("essence_presence_", i)]]
  
  # Calculate colSums for the dataset
  colsums <- colSums(essence_presence_data == 1)
  
  # Create a data frame with the results
  kf_basidio_list[[paste0("kf_", i)]] <- data.frame(species = colnames(essence_presence_data), all = colsums, row.names = NULL)
}






kf_basidio_added_list <- list()
for (i in 1:11) {
  kf <- kf_basidio_list[[paste0("kf_", i)]]
  
  kf_basidio_added_list[[paste0("kf_added_", i)]] <- kf %>%
    group_by(all) %>%
    summarize(count = n())
  
  
}


kf_basidio_combined <- list()

# Loop through the 11 datasets
for (i in 1:11) {
  kf_added <- kf_basidio_added_list[[paste0("kf_added_", i)]]
  
  #add number of appearances
  kf_added$appearances <- i
  
  #put in list
  kf_basidio_combined[[i]] <- kf_added
}

#bind datasets 
final_kf_basidio_combined <- bind_rows(kf_basidio_combined)

final_kf_basidio_combined$all <- as.character(final_kf_basidio_combined$all)





#####Asco####
invent_asco <- invent %>%
  filter(Phylum == "Ascomycète")

essence_presence_asco_list <- list()

for (i in 1:10) {
  essence_presence_asco_list[[paste0("essence_presence_", i)]] <- invent_asco %>%
    mutate(Identifiant.site = paste0("S", Identifiant.site)) %>%
    group_by(Taxon.fonge) %>%
    filter(n() == i) %>%
    distinct(Essence, Taxon.fonge) %>%
    mutate(present = 1) %>%
    pivot_wider(names_from = Taxon.fonge, values_from = present, values_fill = list(present = 0)) %>%
    as.data.frame()
  
  row.names(essence_presence_asco_list[[paste0("essence_presence_", i)]]) <- essence_presence_asco_list[[paste0("essence_presence_", i)]]$Essence
  essence_presence_asco_list[[paste0("essence_presence_", i)]]$Essence <- NULL
}

essence_presence_asco_list[["essence_presence_11"]] <- invent_asco %>%
  mutate(Identifiant.site = paste0("S", Identifiant.site)) %>%
  group_by(Taxon.fonge) %>%
  filter(n() >= 11) %>%
  distinct(Essence, Taxon.fonge) %>%
  mutate(present = 1) %>%
  pivot_wider(names_from = Taxon.fonge, values_from = present, values_fill = list(present = 0)) %>%
  as.data.frame()

row.names(essence_presence_asco_list[["essence_presence_11"]]) <- essence_presence_asco_list[["essence_presence_11"]]$Essence
essence_presence_asco_list[["essence_presence_11"]]$Essence <- NULL




kf_asco_list <- list()
for (i in 1:11) {
  # Get the essence_presence dataset
  essence_presence_data <- essence_presence_asco_list[[paste0("essence_presence_", i)]]
  
  # Calculate colSums for the dataset
  colsums <- colSums(essence_presence_data == 1)
  
  # Create a data frame with the results
  kf_asco_list[[paste0("kf_", i)]] <- data.frame(species = colnames(essence_presence_data), all = colsums, row.names = NULL)
}






kf_asco_added_list <- list()
for (i in 1:11) {
  kf <- kf_asco_list[[paste0("kf_", i)]]
  
  kf_asco_added_list[[paste0("kf_added_", i)]] <- kf %>%
    group_by(all) %>%
    summarize(count = n())
  
  
}


kf_asco_combined <- list()

# Loop through the 11 datasets
for (i in 1:11) {
  kf_added <- kf_asco_added_list[[paste0("kf_added_", i)]]
  
  #add number of appearances
  kf_added$appearances <- i
  
  #put in list
  kf_asco_combined[[i]] <- kf_added
}

#bind datasets 
final_kf_asco_combined <- bind_rows(kf_asco_combined)

final_kf_asco_combined$all <- as.character(final_kf_asco_combined$all)



#####Family, S1####
kf_all <- data.frame(species = colnames(essence_presence), all = colsums_all, row.names = NULL)

kf_all <- kf_all %>%
  left_join(invent_phylum, by = "species") %>%
  left_join(invent_family, by = "species")


# List of families to keep
families_to_keep <- c("Russulaceae", "Thelephoraceae", "Myxotrichaceae", 
                      "Dothydeomycetes", "Helotiales", "Pyronemataceae")
kf_all$Famille <- as.character(kf_all$Famille) 
kf_all$Famille[!(kf_all$Famille %in% families_to_keep)] <- "Other"
kf_all$Famille <- factor(kf_all$Famille)



kf_all <- kf_all %>%
  filter(!Phylum == "Mucoromycète") %>%
  mutate(Famille = case_when(
    Famille == "Other" & Phylum == "Ascomycète" ~ "Other_Ascomycete",
    Famille == "Other" & Phylum == "Basidiomycète" ~ "Other_Basidiomycete",
    TRUE ~ Famille #keep other family names unchanged
  ))

kf_family <- kf_all %>%
  group_by(Famille, all) %>%
  summarize(count = n()) %>%
  group_by(all)

#####Plotting####
plot_kf_all <- ggplot(final_kf_combined, aes(fill = factor(appearances, levels = 1:11), y = count, x = all)) +
  geom_bar(position = "stack", stat = "identity") +
  scale_fill_viridis_d(direction = -1) +  
  ggtitle("All species") +
  theme_minimal() +
  scale_fill_viridis_d(name = "Number of appearances", direction = -1) +
  labs(x = NULL, y = NULL) +
  theme(plot.title = element_text(hjust = 0.5, size = 16))


plot_kf_basidio <- ggplot(final_kf_basidio_combined, aes(fill = factor(appearances, levels = 1:11), y = count, x = all)) +
  geom_bar(position = "stack", stat = "identity") +
  ggtitle("Basidiomycetes") +
  theme_minimal() +
  scale_fill_viridis_d(name = "Number of appearances", direction = -1) +
  labs(x = NULL, y = NULL) +
  theme(plot.title = element_text(hjust = 0.5, size = 16),
        legend.position = "none")
  

plot_kf_asco <- ggplot(final_kf_asco_combined, aes(fill = factor(appearances, levels = 1:11), y = count, x = all)) +
  geom_bar(position = "stack", stat = "identity") +
  ggtitle("Ascomycetes") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5, size = 16),
        legend.position = "none") +
  labs(x = NULL, y = NULL) +
  scale_fill_viridis_d(name = "Number of appearances", direction = -1)


# reorder for color-gradient purposes
kf_family$Famille <- factor(kf_family$Famille, levels = c(
  "Pyronemataceae", "Myxotrichaceae", "Dothydeomycetes", "Helotiales", "Other_Ascomycete", # Red
  "Russulaceae", "Thelephoraceae", "Other_Basidiomycete" # Blue
))

kf_family$all <- as.character(kf_family$all)
plot_kf_family <- ggplot(kf_family, aes(fill = Famille, y = count, x = all)) +
  geom_bar(position = "stack", stat = "identity") +
  ggtitle("All species: Families") +
  theme(plot.title = element_text(hjust = 0.5, size = 16)) +
  labs(x = NULL, y = NULL) +
  theme_minimal() +
  scale_fill_manual(values = c("Other_Ascomycete" = "#d43d31", 
                               "Other_Basidiomycete" = "#00bfc4ff",
                               "Russulaceae" = "#008b90",
                               "Thelephoraceae" = "#33e6eb",
                               "Dothydeomycetes" = "#f8766dff",
                               "Myxotrichaceae" = "#ff8c42",
                               "Helotiales" = "#ff4b3e",
                               "Pyronemataceae" = "#FFBC27"),
                    name = "Families")


#####
figure_kf <- ggarrange(
  plot_kf_all, 
  ggarrange(plot_kf_basidio, plot_kf_asco, ncol = 1, nrow = 2), 
  ncol = 2, 
  widths = c(2, 1) # Adjust widths for left and right panels
)

figure_kf

fig_s1 <- plot_kf_family
plot_kf_family
```

# Figure 3 - Bipartite network
```{r}
####All sites####
edge <- ess_pres_long %>%
  filter(presence == 1) %>%
  select(-presence) %>%
  rename(from = species, to = fungi)

invent_unique <- invent %>%
  select(Taxon.fonge, Phylum) %>%
  distinct() %>%
  group_by(Taxon.fonge) %>%
  slice(1)

edge <- edge %>%
  left_join(invent_unique %>% select(Taxon.fonge, Phylum), by = c("to" = "Taxon.fonge"))


to_phylum <- edge %>% select(to, Phylum) %>% distinct()

for (i in 1:nrow(to_phylum)) {
  node <- to_phylum$to[i]
  phylum <- to_phylum$Phylum[i]

  if (phylum == "Ascomycète") {
    colors[node] <- "#f8766dff"
  } else if (phylum == "Basidiomycète") {
    colors[node] <- "#00bfc4ff"
  } else if (phylum == "Mucoromycète") {
    colors[node] <- "#6800d1ff"
  }
}


from_categories <- data.frame(
  species = unique(edge$from),  # Assuming you know these species
  Category = c("Pioneer species", "Castanea sativa", "End of succession",  # Define categories manually
               "End of succession", "Pioneer species", "End of succession",
               "End of succession", "Pioneer species", "Pioneer species")
)

edge <- edge %>%
  left_join(from_categories, by = c("from" = "species"))

from_category <- edge %>% select(from, Category) %>% distinct()

for (i in 1:nrow(from_category)) {
  node <- from_category$from[i]
  category <- from_category$Category[i]

  if (category == "Pioneer species") {
    colors[node] <- "#ffca22ff"  # Example color for Category 1
  } else if (category == "End of succession") {
    colors[node] <- "lightblue"  # Example color for Category 2
  } else if (category == "Castanea sativa") {
    colors[node] <- "chartreuse4"  # Example color for Category 3
  }
}




net_1 <- graph_from_data_frame(d = edge, directed = FALSE)
#LAYOUT
#layout <- layout_with_fr(net_1, niter = 10000)
layout <- layout_nicely(net_1)
#COLOR
nodes <- unique(c(edge$from, edge$to))
V(net_1)$color <- colors[as.character(V(net_1)$name)]
#SIZE
V(net_1)$size <- ifelse(V(net_1)$name %in% edge$from, 10, 2)
V(net_1)$degree <- degree(net_1)
#NUMBERS AS NAMES
from_vertices <- unique(edge$from)
vertex_labels <- setNames(as.character(1:length(from_vertices)), from_vertices)
V(net_1)$label <- ifelse(V(net_1)$name %in% from_vertices, vertex_labels[V(net_1)$name], "")





#####Plotting####
plot(net_1, layout = layout)

```

# Figure 4 - Upset plot
```{r}
#####Setup####
casta_fungi <- list()

for (tree in rownames(essence_presence_casta)) {
  # Find fungi species with presence (1) for the current tree
  fungi_present <- colnames(essence_presence_casta)[essence_presence_casta[tree, ] == 1]
  
  # Create a one-column matrix with fungi names as rows
  casta_fungi[[tree]] <- matrix(fungi_present, ncol = 1, dimnames = list(NULL, tree))
}


casta_fungi <- lapply(casta_fungi, as.data.frame)




fagaceae <- bind_rows(
  casta_fungi$`Fagus sylvatica`,  
  casta_fungi$`Quercus pubescens`,
  casta_fungi$`Quercus ilex`
) %>%
  pivot_longer(cols = everything(), values_to = "fagaceae") %>%
  filter(!is.na(fagaceae)) %>%
  select(fagaceae) %>%
  distinct()

pinaceae <- casta_fungi$`Pinus spp.`
ericaceae <- casta_fungi$`Arbutus unedo`

other_families <- bind_rows(
  casta_fungi$`Arbutus unedo`,
  casta_fungi$`Cistus salviifolius`,
  casta_fungi$`Ostrya carpinifolia`
) %>%
  pivot_longer(cols = everything(), values_to = "other_families") %>%
  filter(!is.na(other_families)) %>%
  select(other_families) %>%
  distinct()


fagaceae <- fagaceae$fagaceae
pinaceae <- pinaceae$`Pinus spp.`
ericaceae <- ericaceae$`Arbutus unedo`
other_families <- other_families$other_families
#####Plotting####

upset <- list(Fagaceae = fagaceae, 
              Pinaceae = pinaceae, 
              Ericaceae = ericaceae, 
              Other_families = other_families)
venn <- Venn(upset)
plot_upset(venn)
```


#Figure 5

