---
title: "Myco_Corse_2"
author: "Malo"
date: "2024-09-16"
output: html_document
---

```{r setup, include = FALSE}
# library(betareg)
# library(emmeans)
# library(MuMIn)
# options(na.action = "na.fail")
# library(lmtest)
library(ggplot2)
library(ggpubr)
library(ggsignif)
library(cowplot)
library(investr)
library(dplyr)
library(tidyr)
# library(lme4)
library(vegan)
library(plotly)
library(stats)



library(readxl)
library(psych)
library(tidyr)
library(ggplot2)
library(dplyr)
library(ade4)
library(VIM)
library(vegan)
library(reshape2)
library(plotly)
library(tidyverse)
library(lme4)
library(lmerTest)
library(nlme)
library(MuMIn)
library(DHARMa)
library(tibble)


library(igraph)
library(ggraph)
library(networkD3)

library(knitr)
library(kableExtra)
```

```{r, include = FALSE}
invent_seq <- read.csv(file = "inventory_sequencing1.csv", header = T, stringsAsFactors = T)
invent_a <- invent_seq[invent_seq$Sequencage == "a",]
invent <- read.csv(file = "inventory_sequencing1.csv", header = T, stringsAsFactors = T)

invent_s7 <- invent[invent$Identifiant.site == "7",]
count_phylum_s7 <- invent_s7 %>%
  group_by(Phylum) %>%
  summarize(count =n())

invent_s14 <- invent[invent$Identifiant.site == "14",]
count_phylum_s14 <- invent_s14 %>%
  group_by(Phylum) %>%
  summarize(count =n())

invent_s15 <- invent[invent$Identifiant.site == "15",]
count_phylum_s15 <- invent_s15 %>%
  group_by(Phylum) %>%
  summarize(count =n())

```

#1. Phylums et familles
##1.1 Camemberts
```{r, include = FALSE}


count_phylum_a <- invent_a %>%
  group_by(Phylum) %>%
  summarize(count =n())

invent_a_s7 <- invent_a[invent_a$Identifiant.site == "7",]
count_phylum_a_s7 <- invent_a_s7 %>%
  group_by(Phylum) %>%
  summarize(count =n())

invent_a_s14 <- invent_a[invent_a$Identifiant.site == "14",]
count_phylum_a_s14 <- invent_a_s14 %>%
  group_by(Phylum) %>%
  summarize(count =n())

invent_a_s15 <- invent_a[invent_a$Identifiant.site == "15",]
count_phylum_a_s15 <- invent_a_s15 %>%
  group_by(Phylum) %>%
  summarize(count =n())


#####Tous sites confondus####
count_phylum_a <- count_phylum_a %>%
  mutate(percentage = round((count / sum(count)) * 100,2))


plot_phy_a_all <- ggplot(count_phylum_a, aes(x="", y=count, fill=Phylum)) +
  ggtitle("Tous sites confondus") +
  geom_bar(stat="identity", width=1) +
  coord_polar("y", start=0) +
  geom_text(aes(label = paste0(percentage, "%")), position = position_stack(vjust=0.5)) +
  labs(x = NULL, y = NULL, fill = NULL) +
  scale_fill_manual(values = c("Ascomycète" = "#f8766dff", 
                               "Basidiomycète" = "#00bfc4ff", 
                               "Mucoromycète" = "#6800d1ff"))


#####Site 7####
count_phylum_a_s7 <- count_phylum_a_s7 %>%
  mutate(percentage = round((count / sum(count)) * 100,2))

plot_phy_a_7 <- ggplot(count_phylum_a_s7, aes(x="", y=count, fill=Phylum)) +
  ggtitle("Site 7") +
  geom_bar(stat="identity", width=1) +
  coord_polar("y", start=0) +
  geom_text(aes(label = paste0(percentage, "%")), position = position_stack(vjust=0.5)) +
  labs(x = NULL, y = NULL, fill = NULL) +
  scale_fill_manual(values = c("Ascomycète" = "#f8766dff", 
                               "Basidiomycète" = "#00bfc4ff", 
                               "Mucoromycète" = "#6800d1ff"))

#####Site 14####
count_phylum_a_s14 <- count_phylum_a_s14 %>%
  mutate(percentage = round((count / sum(count)) * 100,2))

plot_phy_a_14 <- ggplot(count_phylum_a_s14, aes(x="", y=count, fill=Phylum)) +
  ggtitle("Site 14") +
  geom_bar(stat="identity", width=1) +
  coord_polar("y", start=0) +
  geom_text(aes(label = paste0(percentage, "%")), position = position_stack(vjust=0.5)) +
  labs(x = NULL, y = NULL, fill = NULL) + 
  scale_fill_manual(values = c("Ascomycète" = "#f8766dff", 
                               "Basidiomycète" = "#00bfc4ff", 
                               "Mucoromycète" = "#6800d1ff"))


#####Site 15####
count_phylum_a_s15 <- count_phylum_a_s15 %>%
  mutate(percentage = round((count / sum(count)) * 100,2))

plot_phy_a_15 <- ggplot(count_phylum_a_s15, aes(x="", y=count, fill=Phylum)) +
  ggtitle("Site 15") +
  geom_bar(stat="identity", width=1) +
  coord_polar("y", start=0) +
  geom_text(aes(label = paste0(percentage, "%")), position = position_stack(vjust=0.5)) +
  labs(x = NULL, y = NULL, fill = NULL) +
  scale_fill_manual(values = c("Ascomycète" = "#f8766dff", 
                               "Basidiomycète" = "#00bfc4ff", 
                               "Mucoromycète" = "#6800d1ff"))


plot_phy_a <- ggarrange(plot_phy_a_all, plot_phy_a_7, plot_phy_a_14, plot_phy_a_15, ncol = 2, nrow = 2)

```


```{r}
plot_phy_a
```

##1.2 Tableaux familles

```{r, include = FALSE}
tab_all <- invent %>%
  group_by(Famille) %>%
  summarize(count = n()) %>%
  arrange(desc(count))

tab_a_all <- invent_a %>%
  group_by(Famille) %>%
  summarize(count = n()) %>%
  arrange(desc(count))



#S7
tab_s7 <- invent_s7%>%
  group_by(Famille) %>%
  summarize(count = n()) %>%
  arrange(desc(count))

tab_a_s7 <- invent_a_s7%>%
  group_by(Famille) %>%
  summarize(count = n()) %>%
  arrange(desc(count))

#S14
tab_s14 <- invent_s14%>%
  group_by(Famille) %>%
  summarize(count = n()) %>%
  arrange(desc(count))

tab_a_s14 <- invent_a_s14%>%
  group_by(Famille) %>%
  summarize(count = n()) %>%
  arrange(desc(count))

#S15
tab_s15 <- invent_s15%>%
  group_by(Famille) %>%
  summarize(count = n()) %>%
  arrange(desc(count))

tab_a_s15 <- invent_a_s15%>%
  group_by(Famille) %>%
  summarize(count = n()) %>%
  arrange(desc(count))

```

```{r}
#All
kable(tab_all, col.names = c("Family", "Count"), format = "html", table.attr = "class='table table-striped'") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
kable(tab_a_all, col.names = c("Family", "Count"), format = "html", table.attr = "class='table table-striped'") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))


#S7
kable(tab_s7, col.names = c("Family", "Count"), format = "html", table.attr = "class='table table-striped'") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
kable(tab_a_s7, col.names = c("Family", "Count"), format = "html", table.attr = "class='table table-striped'") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))

#S14
kable(tab_s14, col.names = c("Family", "Count"), format = "html", table.attr = "class='table table-striped'") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
kable(tab_a_s7, col.names = c("Family", "Count"), format = "html", table.attr = "class='table table-striped'") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))

#S15
kable(tab_s15, col.names = c("Family", "Count"), format = "html", table.attr = "class='table table-striped'") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
kable(tab_a_s15, col.names = c("Family", "Count"), format = "html", table.attr = "class='table table-striped'") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))

```




#2. Courbes de raréfaction

```{r}
abundance <- invent %>%
  mutate(Identifiant.site = paste0("S", Identifiant.site)) %>%
  group_by(Identifiant.site, Taxon.fonge) %>%
  summarize(count = n()) %>%
  pivot_wider(names_from = Taxon.fonge, values_from = count, values_fill = list(count = 0))

abundance <- as.data.frame(abundance)
row.names(abundance) <- abundance$Identifiant.site
abundance$Identifiant.site <- NULL


spAb <- rowSums(abundance)
spAb
#Le + petit effort d'échantillonnage : S7 avec 163

raremin <- min(rowSums(abundance))

sRare <- rarefy(abundance, raremin)
sRare


rarecurve(abundance, col = "blue")

```


#3. Réseaux projetés pondérés et colorés
```{r, include = FALSE}
essence_presence <- invent %>%
  mutate(Identifiant.site = paste0("S", Identifiant.site)) %>%
  distinct(Essence, Taxon.fonge) %>%
  mutate(present = 1) %>%
  pivot_wider(names_from = Taxon.fonge, values_from = present, values_fill = list(present = 0))
essence_presence <- as.data.frame(essence_presence)

row.names(essence_presence) <- essence_presence$Essence
essence_presence$Essence <- NULL

essence_presence_matrix <- as.matrix(essence_presence)

double_presence <- essence_presence_matrix %*% t(essence_presence_matrix)


essence_presence <- invent %>%
  mutate(Identifiant.site = paste0("S", Identifiant.site)) %>%
  distinct(Essence, Taxon.fonge) %>%
  mutate(present = 1) %>%
  pivot_wider(names_from = Taxon.fonge, values_from = present, values_fill = list(present = 0))
essence_presence <- as.data.frame(essence_presence)

row.names(essence_presence) <- essence_presence$Essence
essence_presence$Essence <- NULL

essence_presence_matrix <- as.matrix(essence_presence)

double_presence <- essence_presence_matrix %*% t(essence_presence_matrix)

# 
essence_presence$species <- rownames(essence_presence)
ess_pres_long <- essence_presence %>%
  pivot_longer(cols=1:169, names_to="fungi",
               values_to="presence")
# 
# double_presence_df <- ess_pres_long %>%
#   filter(presence == 1) %>%
#   inner_join(ess_pres_long %>% filter(presence == 1),
#               by = "fungi",
#               suffix = c("_1", "_2")) %>%
#   group_by(species_1, species_2) %>%
#   summarize(double_presence = n(), .groups = 'drop')
#
# ## all of this is the same thing as double_presence <- essence_presence_matrix %*% t(essence_presence_matrix)

#S7
essence_presence_s7 <- invent_s7 %>%
  mutate(Identifiant.site = paste0("S", Identifiant.site)) %>%
  distinct(Essence, Taxon.fonge) %>%
  mutate(present = 1) %>%
  pivot_wider(names_from = Taxon.fonge, values_from = present, values_fill = list(present = 0))
essence_presence_s7 <- as.data.frame(essence_presence_s7)

row.names(essence_presence_s7) <- essence_presence_s7$Essence
essence_presence_s7$Essence <- NULL

essence_presence_matrix_s7 <- as.matrix(essence_presence_s7)
double_presence_s7 <- essence_presence_matrix_s7 %*% t(essence_presence_matrix_s7)

#S14
essence_presence_s14 <- invent_s14 %>%
  mutate(Identifiant.site = paste0("S", Identifiant.site)) %>%
  distinct(Essence, Taxon.fonge) %>%
  mutate(present = 1) %>%
  pivot_wider(names_from = Taxon.fonge, values_from = present, values_fill = list(present = 0))
essence_presence_s14 <- as.data.frame(essence_presence_s14)

row.names(essence_presence_s14) <- essence_presence_s14$Essence
essence_presence_s14$Essence <- NULL

essence_presence_matrix_s14 <- as.matrix(essence_presence_s14)
double_presence_s14 <- essence_presence_matrix_s14 %*% t(essence_presence_matrix_s14)

#S15
essence_presence_s15 <- invent_s15 %>%
  mutate(Identifiant.site = paste0("S", Identifiant.site)) %>%
  distinct(Essence, Taxon.fonge) %>%
  mutate(present = 1) %>%
  pivot_wider(names_from = Taxon.fonge, values_from = present, values_fill = list(present = 0))
essence_presence_s15 <- as.data.frame(essence_presence_s15)

row.names(essence_presence_s15) <- essence_presence_s15$Essence
essence_presence_s15$Essence <- NULL

essence_presence_matrix_s15 <- as.matrix(essence_presence_s15)
double_presence_s15 <- essence_presence_matrix_s15 %*% t(essence_presence_matrix_s15)
```

```{r, include = FALSE}
apex <- invent %>%
  group_by(Essence) %>%
  summarize(apex = n())
apex <- as.data.frame(apex)
row.names(apex) <- apex$Essence
apex$Essence <- NULL





#WEIGHTING DOUBLE PRESENCE
# Sampling effort
sampling_effort <- c(84,206,43,20,73,69,66,22,13)
# Calculate weights
weights <- outer(sampling_effort, sampling_effort, function(x, y) 1 / sqrt(x * y))
# Apply weights to the data frame
weighted_double_pres <- double_presence * weights



cat_essence <- c("Pioneer species", "Castanea sativa", "End of succession", "End of succession", "Pioneer species", "End of succession", "End of succession", "Pioneer species", "Pioneer species")
names(cat_essence) <- rownames(weighted_double_pres)
df_categories <- data.frame(node = rownames(weighted_double_pres), category = cat_essence)



#ENLEVER LES DOUBLONS
weighted_double_pres_norep <- as.data.frame(weighted_double_pres) %>%
  rownames_to_column(var = "from") %>%
  pivot_longer(-from, names_to = "to", values_to = "value") %>%
  filter(from != to)  

weighted_double_pres_norep <- weighted_double_pres_norep %>%
  mutate(pair = pmap_chr(list(from, to), ~ paste(sort(c(..1, ..2)), collapse = "-"))) %>%
  distinct(pair, .keep_all = TRUE) %>%
  select(-pair)  

proj_all <- weighted_double_pres_norep

proj_all <- proj_all %>%
  left_join(df_categories, by = c("from" = "node")) %>%
  rename(from_category = category) %>%
  left_join(df_categories, by = c("to" = "node")) %>%
  rename(to_category = category)

proj_all$color_edge <- ifelse(proj_all$from == "Castanea sativa" | proj_all$to == "Castanea sativa", "lightgreen", "lightgrey")
graph_pond_all <- graph_from_data_frame(proj_all, directed = FALSE)

proj_all <- ggraph(graph_pond_all, layout = 'circle') +
  geom_edge_fan(aes(edge_width = value, color = color_edge), curvature = 0.1) +
  geom_node_point(aes(color = cat_essence, size = 3), show.legend = T) +
  geom_node_text(aes(label = name), vjust = 1.5) +
  scale_edge_width(range = c(0.1, 3)) +
  scale_color_manual(values = c("End of succession" = "lightblue", 
                                "Pioneer species" = "#ffca22ff", 
                                "Castanea sativa" = "chartreuse4")) +
  scale_edge_color_manual(values = c("lightgrey" = "lightgrey",
                                     "lightgreen" = "lightgreen")) +
  theme_void() +
  theme(legend.position = "none")



```


##3.1 Tous sites confondus
```{r}
proj_all
```


##3.2 Site 7
```{r, include = FALSE}
#S7
essence_presence_s7 <- invent_s7 %>%
  mutate(Identifiant.site = paste0("S", Identifiant.site)) %>%
  distinct(Essence, Taxon.fonge) %>%
  mutate(present = 1) %>%
  pivot_wider(names_from = Taxon.fonge, values_from = present, values_fill = list(present = 0))
essence_presence_s7 <- as.data.frame(essence_presence_s7)

row.names(essence_presence_s7) <- essence_presence_s7$Essence
essence_presence_s7$Essence <- NULL

essence_presence_matrix_s7 <- as.matrix(essence_presence_s7)
double_presence_s7 <- essence_presence_matrix_s7 %*% t(essence_presence_matrix_s7)




apex_s7 <- invent_s7 %>%
  group_by(Essence) %>%
  summarize(apex = n())
apex_s7 <- as.data.frame(apex_s7)
row.names(apex_s7) <- apex_s7$Essence
apex_s7$Essence <- NULL



invent_s7 %>%
  group_by(Essence) %>%
  summarize(count = n())


#WEIGHTING DOUBLE PRESENCE
# Sampling effort
sampling_effort_s7 <- c(70,20,19,14,14,13,13)
# Calculate weights
weights_s7 <- outer(sampling_effort_s7, sampling_effort_s7, function(x, y) 1 / sqrt(x * y))
# Apply weights to the data frame
weighted_double_pres_s7 <- double_presence_s7 * weights_s7

#ENLEVER LES DOUBLONS
weighted_double_pres_norep_s7 <- as.data.frame(weighted_double_pres_s7) %>%
  rownames_to_column(var = "from") %>%
  pivot_longer(-from, names_to = "to", values_to = "value") %>%
  filter(from != to)  

weighted_double_pres_norep_s7 <- weighted_double_pres_norep_s7 %>%
  mutate(pair = pmap_chr(list(from, to), ~ paste(sort(c(..1, ..2)), collapse = "-"))) %>%
  distinct(pair, .keep_all = TRUE) %>%
  select(-pair)  


cat_essence_s7 <- c("Castanea sativa", "End of succession", "Pioneer species", "End of succession", "Pioneer species", "Pioneer species", "End of succession")
names(cat_essence_s7) <- rownames(weighted_double_pres_s7)
df_categories_s7 <- data.frame(node = rownames(weighted_double_pres_s7), category = cat_essence_s7)


proj_all_s7 <- weighted_double_pres_norep_s7

proj_all_s7 <- proj_all_s7 %>%
  left_join(df_categories_s7, by = c("from" = "node")) %>%
  rename(from_category = category) %>%
  left_join(df_categories_s7, by = c("to" = "node")) %>%
  rename(to_category = category)

proj_all_s7$color_edge <- ifelse(proj_all_s7$from == "Castanea sativa" | proj_all_s7$to == "Castanea sativa", "lightgreen", "lightgrey")
graph_pond_all_s7 <- graph_from_data_frame(proj_all_s7, directed = FALSE)

projected_s7 <- ggraph(graph_pond_all_s7, layout = 'circle') +
  geom_edge_arc(aes(edge_width = value, color = color_edge), strength = 0.5) +
  geom_node_point(aes(color = cat_essence_s7, size = 3), show.legend = T) +
  geom_node_text(aes(label = name), vjust = 1.5) +
  scale_edge_width(range = c(0.1, 3)) +
  scale_color_manual(values = c("End of succession" = "lightblue", 
                                "Pioneer species" = "#ffca22ff", 
                                "Castanea sativa" = "chartreuse4")) +
  scale_edge_color_manual(values = c("lightgrey" = "lightgrey",
                                     "lightgreen" = "lightgreen")) +
  theme_void() +
  theme(legend.position = "none")

```

```{r}
projected_s7
```


##3.3 Site 14
```{r, include = FALSE}
#S14
essence_presence_s14 <- invent_s14 %>%
  mutate(Identifiant.site = paste0("S", Identifiant.site)) %>%
  distinct(Essence, Taxon.fonge) %>%
  mutate(present = 1) %>%
  pivot_wider(names_from = Taxon.fonge, values_from = present, values_fill = list(present = 0))
essence_presence_s14 <- as.data.frame(essence_presence_s14)

row.names(essence_presence_s14) <- essence_presence_s14$Essence
essence_presence_s14$Essence <- NULL

essence_presence_matrix_s14 <- as.matrix(essence_presence_s14)
double_presence_s14 <- essence_presence_matrix_s14 %*% t(essence_presence_matrix_s14)




apex_s14 <- invent_s14 %>%
  group_by(Essence) %>%
  summarize(apex = n())
apex_s14 <- as.data.frame(apex_s14)
row.names(apex_s14) <- apex_s14$Essence
apex_s14$Essence <- NULL



invent_s14 %>%
  group_by(Essence) %>%
  summarize(count = n())


#WEIGHTING DOUBLE PRESENCE
# Sampling effort
sampling_effort_s14 <- c(18,74,8,38,26,7)
# Calculate weights
weights_s14 <- outer(sampling_effort_s14, sampling_effort_s14, function(x, y) 1 / sqrt(x * y))
# Apply weights to the data frame
weighted_double_pres_s14 <- double_presence_s14 * weights_s14

#ENLEVER LES DOUBLONS
weighted_double_pres_norep_s14 <- as.data.frame(weighted_double_pres_s14) %>%
  rownames_to_column(var = "from") %>%
  pivot_longer(-from, names_to = "to", values_to = "value") %>%
  filter(from != to)  

weighted_double_pres_norep_s14 <- weighted_double_pres_norep_s14 %>%
  mutate(pair = pmap_chr(list(from, to), ~ paste(sort(c(..1, ..2)), collapse = "-"))) %>%
  distinct(pair, .keep_all = TRUE) %>%
  select(-pair)  


cat_essence_s14 <- c("Pioneer species", "Castanea sativa", "Pioneer species", "Pioneer species", "End of succession", "End of succession")
names(cat_essence_s14) <- rownames(weighted_double_pres_s14)
df_categories_s14 <- data.frame(node = rownames(weighted_double_pres_s14), category = cat_essence_s14)


proj_all_s14 <- weighted_double_pres_norep_s14

proj_all_s14 <- proj_all_s14 %>%
  left_join(df_categories_s14, by = c("from" = "node")) %>%
  rename(from_category = category) %>%
  left_join(df_categories_s14, by = c("to" = "node")) %>%
  rename(to_category = category)

proj_all_s14$color_edge <- ifelse(proj_all_s14$from == "Castanea sativa" | proj_all_s14$to == "Castanea sativa", "lightgreen", "lightgrey")
graph_pond_all_s14 <- graph_from_data_frame(proj_all_s14, directed = FALSE)

projected_s14 <- ggraph(graph_pond_all_s14, layout = 'circle') +
  geom_edge_arc(aes(edge_width = value, color = color_edge), strength = 0.5) +
  geom_node_point(aes(color = cat_essence_s14, size = 3), show.legend = T) +
  geom_node_text(aes(label = name), vjust = 1.5) +
  scale_edge_width(range = c(0.1, 3)) +
  scale_color_manual(values = c("End of succession" = "lightblue", 
                                "Pioneer species" = "#ffca22ff", 
                                "Castanea sativa" = "chartreuse4")) +
  scale_edge_color_manual(values = c("lightgrey" = "lightgrey",
                                     "lightgreen" = "lightgreen")) +
  theme_void() +
  theme(legend.position = "none")

```

```{r}
projected_s14
```


##3.4 Site 15

```{r, include = FALSE}
#s15
essence_presence_s15 <- invent_s15 %>%
  mutate(Identifiant.site = paste0("S", Identifiant.site)) %>%
  distinct(Essence, Taxon.fonge) %>%
  mutate(present = 1) %>%
  pivot_wider(names_from = Taxon.fonge, values_from = present, values_fill = list(present = 0))
essence_presence_s15 <- as.data.frame(essence_presence_s15)

row.names(essence_presence_s15) <- essence_presence_s15$Essence
essence_presence_s15$Essence <- NULL

essence_presence_matrix_s15 <- as.matrix(essence_presence_s15)
double_presence_s15 <- essence_presence_matrix_s15 %*% t(essence_presence_matrix_s15)




apex_s15 <- invent_s15 %>%
  group_by(Essence) %>%
  summarize(apex = n())
apex_s15 <- as.data.frame(apex_s15)
row.names(apex_s15) <- apex_s15$Essence
apex_s15$Essence <- NULL



invent_s15 %>%
  group_by(Essence) %>%
  summarize(count = n())


#WEIGHTING DOUBLE PRESENCE
# Sampling effort
sampling_effort_s15 <- c(36,62,43,46,26,49)
# Calculate weights
weights_s15 <- outer(sampling_effort_s15, sampling_effort_s15, function(x, y) 1 / sqrt(x * y))
# Apply weights to the data frame
weighted_double_pres_s15 <- double_presence_s15 * weights_s15

#ENLEVER LES DOUBLONS
weighted_double_pres_norep_s15 <- as.data.frame(weighted_double_pres_s15) %>%
  rownames_to_column(var = "from") %>%
  pivot_longer(-from, names_to = "to", values_to = "value") %>%
  filter(from != to)  

weighted_double_pres_norep_s15 <- weighted_double_pres_norep_s15 %>%
  mutate(pair = pmap_chr(list(from, to), ~ paste(sort(c(..1, ..2)), collapse = "-"))) %>%
  distinct(pair, .keep_all = TRUE) %>%
  select(-pair)  


cat_essence_s15 <- c("Pioneer species", "Castanea sativa", "End of succession", "Pioneer species", "End of succession", "End of succession")
names(cat_essence_s15) <- rownames(weighted_double_pres_s15)
df_categories_s15 <- data.frame(node = rownames(weighted_double_pres_s15), category = cat_essence_s15)


proj_all_s15 <- weighted_double_pres_norep_s15

proj_all_s15 <- proj_all_s15 %>%
  left_join(df_categories_s15, by = c("from" = "node")) %>%
  rename(from_category = category) %>%
  left_join(df_categories_s15, by = c("to" = "node")) %>%
  rename(to_category = category)

proj_all_s15$color_edge <- ifelse(proj_all_s15$from == "Castanea sativa" | proj_all_s15$to == "Castanea sativa", "lightgreen", "lightgrey")
graph_pond_all_s15 <- graph_from_data_frame(proj_all_s15, directed = FALSE)

projected_s15 <- ggraph(graph_pond_all_s15, layout = 'circle') +
  geom_edge_arc(aes(edge_width = value, color = color_edge), strength = 0.5) +
  geom_node_point(aes(color = cat_essence_s15, size = 3), show.legend = T) +
  geom_node_text(aes(label = name), vjust = 1.5) +
  scale_edge_width(range = c(0.1, 3)) +
  scale_color_manual(values = c("End of succession" = "lightblue", 
                                "Pioneer species" = "#ffca22ff", 
                                "Castanea sativa" = "chartreuse4")) +
  scale_edge_color_manual(values = c("lightgrey" = "lightgrey",
                                     "lightgreen" = "lightgreen")) +
  theme_void() +
  theme(legend.position = "none")

```

```{r}
projected_s15
```



#4. Réseau bipartite
##4.1 Tous sites confondus
```{r, include = FALSE}

#####Tous sites confondus####
# edge <- ess_pres_long %>%
#   filter(presence == 1) %>%
#   select(-presence) %>%
#   rename(from = species, to = fungi)
# 
# invent_unique <- invent %>%
#   select(Taxon.fonge, Phylum) %>%
#   distinct() %>%
#   group_by(Taxon.fonge) %>%
#   slice(1)  
# 
# edge <- edge %>%
#   left_join(invent_unique %>% select(Taxon.fonge, Phylum), by = c("to" = "Taxon.fonge"))
# 
# 
# to_phylum <- edge %>% select(to, Phylum) %>% distinct()
# 
# for (i in 1:nrow(to_phylum)) {
#   node <- to_phylum$to[i]
#   phylum <- to_phylum$Phylum[i]
#   
#   if (phylum == "Ascomycète") {
#     colors[node] <- "#f8766dff"
#   } else if (phylum == "Basidiomycète") {
#     colors[node] <- "#00bfc4ff"
#   } else if (phylum == "Mucoromycète") {
#     colors[node] <- "#6800d1ff"
#   }
# }
# 
# 
# from_categories <- data.frame(
#   species = unique(edge$from),  # Assuming you know these species
#   Category = c("Pioneer species", "Castanea sativa", "End of succession",  # Define categories manually
#                "End of succession", "Pioneer species", "End of succession", 
#                "End of succession", "Pioneer species", "Pioneer species")
# )
# 
# edge <- edge %>%
#   left_join(from_categories, by = c("from" = "species"))
# 
# from_category <- edge %>% select(from, Category) %>% distinct()
# 
# for (i in 1:nrow(from_category)) {
#   node <- from_category$from[i]
#   category <- from_category$Category[i]
#   
#   if (category == "Pioneer species") {
#     colors[node] <- "#ffca22ff"  # Example color for Category 1
#   } else if (category == "End of succession") {
#     colors[node] <- "lightblue"  # Example color for Category 2
#   } else if (category == "Castanea sativa") {
#     colors[node] <- "chartreuse4"  # Example color for Category 3
#   }
# }
# 
# 
# 
# 
# net_1 <- graph_from_data_frame(d = edge, directed = FALSE)
# #LAYOUT
# layout <- layout_with_fr(net_1, niter = 10000)
# #COLOR
# nodes <- unique(c(edge$from, edge$to))
# V(net_1)$color <- colors[as.character(V(net_1)$name)]
# #SIZE
# V(net_1)$size <- ifelse(V(net_1)$name %in% edge$from, 10, 2)
# V(net_1)$degree <- degree(net_1)
# #NUMBERS AS NAMES
# from_vertices <- unique(edge$from)
# vertex_labels <- setNames(as.character(1:length(from_vertices)), from_vertices)
# V(net_1)$label <- ifelse(V(net_1)$name %in% from_vertices, vertex_labels[V(net_1)$name], "")


```

```{r}
#PLOT
# plot(net_1, layout = layout,
#      main = "Réseau d'interaction tous sites confondus",
# )
```


##4.2 Site 7
```{r, include = FALSE}
#####Site 7####
edge_s7 <- ess_pres_long_s7 %>%
  filter(presence == 1) %>%
  select(-presence) %>%
  rename(from = species, to = fungi)

invent_unique_s7 <- invent_s7 %>%
  select(Taxon.fonge, Phylum) %>%
  distinct() %>%
  group_by(Taxon.fonge) %>%
  slice(1)

edge_s7 <- edge_s7 %>%
  left_join(invent_unique_s7 %>% select(Taxon.fonge, Phylum), by = c("to" = "Taxon.fonge"))


to_phylum_s7 <- edge_s7 %>% select(to, Phylum) %>% distinct()

for (i in 1:nrow(to_phylum_s7)) {
  node <- to_phylum_s7$to[i]
  phylum <- to_phylum_s7$Phylum[i]

  if (phylum == "Ascomycète") {
    colors_s7[node] <- "#f8766dff"
  } else if (phylum == "Basidiomycète") {
    colors_s7[node] <- "#00bfc4ff"
  } else if (phylum == "Mucoromycète") {
    colors_s7[node] <- "#6800d1ff"
  }
}


from_categories_s7 <- data.frame(
  species = unique(edge_s7$from),
  Category = c("Castanea sativa", "End of succession",
               "Pioneer species", "End of succession",
               "Pioneer species", "Pioneer species", "End of succession")
)

edge_s7 <- edge_s7 %>%
  left_join(from_categories_s7, by = c("from" = "species"))

from_category_s7 <- edge_s7 %>% select(from, Category) %>% distinct()

for (i in 1:nrow(from_category_s7)) {
  node <- from_category_s7$from[i]
  category <- from_category_s7$Category[i]

  if (category == "Pioneer species") {
    colors_s7[node] <- "#ffca22ff"  # Example color for Category 1
  } else if (category == "End of succession") {
    colors_s7[node] <- "lightblue"  # Example color for Category 2
  } else if (category == "Castanea sativa") {
    colors_s7[node] <- "chartreuse4"  # Example color for Category 3
  }
}




net_s7 <- graph_from_data_frame(d = edge_s7, directed = FALSE)
#LAYOUT
layout <- layout_with_fr(net_s7, niter = 10000)
#COLOR
nodes_s7 <- unique(c(edge_s7$from, edge_s7$to))
V(net_s7)$color <- colors_s7[as.character(V(net_s7)$name)]
#SIZE
V(net_s7)$size <- ifelse(V(net_s7)$name %in% edge_s7$from, 10, 2)
V(net_s7)$degree <- degree(net_s7)
#NUMBERS AS NAMES
from_vertices_s7 <- unique(edge_s7$from)
vertex_labels_s7 <- setNames(as.character(1:length(from_vertices_s7)), from_vertices_s7)
V(net_s7)$label <- ifelse(V(net_s7)$name %in% from_vertices_s7, vertex_labels[V(net_s7)$name], "")

edge_s7 <- ess_pres_long_s7 %>%
  filter(presence == 1) %>%
  select(-presence) %>%
  rename(from = species, to = fungi)

invent_unique_s7 <- invent_s7 %>%
  select(Taxon.fonge, Phylum) %>%
  distinct() %>%
  group_by(Taxon.fonge) %>%
  slice(1)

edge_s7 <- edge_s7 %>%
  left_join(invent_unique_s7 %>% select(Taxon.fonge, Phylum), by = c("to" = "Taxon.fonge"))


to_phylum_s7 <- edge_s7 %>% select(to, Phylum) %>% distinct()

for (i in 1:nrow(to_phylum_s7)) {
  node <- to_phylum_s7$to[i]
  phylum <- to_phylum_s7$Phylum[i]

  if (phylum == "Ascomycète") {
    colors_s7[node] <- "#f8766dff"
  } else if (phylum == "Basidiomycète") {
    colors_s7[node] <- "#00bfc4ff"
  } else if (phylum == "Mucoromycète") {
    colors_s7[node] <- "#6800d1ff"
  }
}


from_categories_s7 <- data.frame(
  species = unique(edge_s7$from),
  Category = c("Castanea sativa", "End of succession",
               "Pioneer species", "End of succession",
               "Pioneer species", "Pioneer species", "End of succession")
)

edge_s7 <- edge_s7 %>%
  left_join(from_categories_s7, by = c("from" = "species"))

from_category_s7 <- edge_s7 %>% select(from, Category) %>% distinct()

for (i in 1:nrow(from_category_s7)) {
  node <- from_category_s7$from[i]
  category <- from_category_s7$Category[i]

  if (category == "Pioneer species") {
    colors_s7[node] <- "#ffca22ff"  # Example color for Category 1
  } else if (category == "End of succession") {
    colors_s7[node] <- "lightblue"  # Example color for Category 2
  } else if (category == "Castanea sativa") {
    colors_s7[node] <- "chartreuse4"  # Example color for Category 3
  }
}




net_s7 <- graph_from_data_frame(d = edge_s7, directed = FALSE)
#LAYOUT
layout <- layout_with_fr(net_s7, niter = 10000)
#COLOR
nodes_s7 <- unique(c(edge_s7$from, edge_s7$to))
V(net_s7)$color <- colors_s7[as.character(V(net_s7)$name)]
#SIZE
V(net_s7)$size <- ifelse(V(net_s7)$name %in% edge_s7$from, 10, 2)
V(net_s7)$degree <- degree(net_s7)
#NUMBERS AS NAMES
from_vertices_s7 <- unique(edge_s7$from)
vertex_labels_s7 <- setNames(as.character(1:length(from_vertices_s7)), from_vertices_s7)
V(net_s7)$label <- ifelse(V(net_s7)$name %in% from_vertices_s7, vertex_labels[V(net_s7)$name], "")


```

```{r}
#PLOT
plot(net_s7, layout = layout,
     main = "Réseau d'interaction du site 7",
)
```

##4.3 Site 14
```{r, include = FALSE}
#####Site 14####
edge_s14 <- ess_pres_long_s14 %>%
  filter(presence == 1) %>%
  select(-presence) %>%
  rename(from = species, to = fungi)

invent_unique_s14 <- invent_s14 %>%
  select(Taxon.fonge, Phylum) %>%
  distinct() %>%
  group_by(Taxon.fonge) %>%
  slice(1)

edge_s14 <- edge_s14 %>%
  left_join(invent_unique_s14 %>% select(Taxon.fonge, Phylum), by = c("to" = "Taxon.fonge"))


to_phylum_s14 <- edge_s14 %>% select(to, Phylum) %>% distinct()

for (i in 1:nrow(to_phylum_s14)) {
  node <- to_phylum_s14$to[i]
  phylum <- to_phylum_s14$Phylum[i]

  if (phylum == "Ascomycète") {
    colors_s14[node] <- "#f8766dff"
  } else if (phylum == "Basidiomycète") {
    colors_s14[node] <- "#00bfc4ff"
  } else if (phylum == "Mucoromycète") {
    colors_s14[node] <- "#6800d1ff"
  }
}


from_categories_s14 <- data.frame(
  species = unique(edge_s14$from),
  Category = c("Castanea sativa", "Pioneer species", "End of succession",
               "Pioneer species", "End of succession", "Pioneer species")
)

edge_s14 <- edge_s14 %>%
  left_join(from_categories_s14, by = c("from" = "species"))

from_category_s14 <- edge_s14 %>% select(from, Category) %>% distinct()

for (i in 1:nrow(from_category_s14)) {
  node <- from_category_s14$from[i]
  category <- from_category_s14$Category[i]

  if (category == "Pioneer species") {
    colors_s14[node] <- "#ffca22ff"  # Example color for Category 1
  } else if (category == "End of succession") {
    colors_s14[node] <- "lightblue"  # Example color for Category 2
  } else if (category == "Castanea sativa") {
    colors_s14[node] <- "chartreuse4"  # Example color for Category 3
  }
}




net_s14 <- graph_from_data_frame(d = edge_s14, directed = FALSE)
#LAYOUT
layout <- layout_with_fr(net_s14, niter = 10000)
#COLOR
nodes_s14 <- unique(c(edge_s14$from, edge_s14$to))
V(net_s14)$color <- colors_s14[as.character(V(net_s14)$name)]
#SIZE
V(net_s14)$size <- ifelse(V(net_s14)$name %in% edge_s14$from, 10, 2)
V(net_s14)$degree <- degree(net_s14)
#NUMBERS AS NAMES
from_vertices_s14 <- unique(edge_s14$from)
vertex_labels_s14 <- setNames(as.character(1:length(from_vertices_s14)), from_vertices_s14)
V(net_s14)$label <- ifelse(V(net_s14)$name %in% from_vertices_s14, vertex_labels[V(net_s14)$name], "")


```

```{r}
#PLOT
plot(net_s14, layout = layout,
     main = "Réseau d'interaction du site 14",
)
```

##4.4 Site 15
```{r, include = FALSE}
####Site 15####
edge_s15 <- ess_pres_long_s15 %>%
  filter(presence == 1) %>%
  select(-presence) %>%
  rename(from = species, to = fungi)

invent_unique_s15 <- invent_s15 %>%
  select(Taxon.fonge, Phylum) %>%
  distinct() %>%
  group_by(Taxon.fonge) %>%
  slice(1)

edge_s15 <- edge_s15 %>%
  left_join(invent_unique_s15 %>% select(Taxon.fonge, Phylum), by = c("to" = "Taxon.fonge"))


to_phylum_s15 <- edge_s15 %>% select(to, Phylum) %>% distinct()

for (i in 1:nrow(to_phylum_s15)) {
  node <- to_phylum_s15$to[i]
  phylum <- to_phylum_s15$Phylum[i]

  if (phylum == "Ascomycète") {
    colors_s15[node] <- "#f8766dff"
  } else if (phylum == "Basidiomycète") {
    colors_s15[node] <- "#00bfc4ff"
  } else if (phylum == "Mucoromycète") {
    colors_s15[node] <- "#6800d1ff"
  }
}


from_categories_s15 <- data.frame(
  species = unique(edge_s15$from),
  Category = c("Pioneer species", "End of succession",
               "Castanea sativa", "End of succession", "End of succession", "Pioneer species")
)

edge_s15 <- edge_s15 %>%
  left_join(from_categories_s15, by = c("from" = "species"))

from_category_s15 <- edge_s15 %>% select(from, Category) %>% distinct()

for (i in 1:nrow(from_category_s15)) {
  node <- from_category_s15$from[i]
  category <- from_category_s15$Category[i]

  if (category == "Pioneer species") {
    colors_s15[node] <- "#ffca22ff"  # Example color for Category 1
  } else if (category == "End of succession") {
    colors_s15[node] <- "lightblue"  # Example color for Category 2
  } else if (category == "Castanea sativa") {
    colors_s15[node] <- "chartreuse4"  # Example color for Category 3
  }
}




net_s15 <- graph_from_data_frame(d = edge_s15, directed = FALSE)
#LAYOUT
layout <- layout_with_fr(net_s15, niter = 10000)
#COLOR
nodes_s15 <- unique(c(edge_s15$from, edge_s15$to))
V(net_s15)$color <- colors_s15[as.character(V(net_s15)$name)]
#SIZE
V(net_s15)$size <- ifelse(V(net_s15)$name %in% edge_s15$from, 10, 2)
V(net_s15)$degree <- degree(net_s15)
#NUMBERS AS NAMES
from_vertices_s15 <- unique(edge_s15$from)
vertex_labels_s15 <- setNames(as.character(1:length(from_vertices_s15)), from_vertices_s15)
V(net_s15)$label <- ifelse(V(net_s15)$name %in% from_vertices_s15, vertex_labels[V(net_s15)$name], "")


```

```{r}
# #PLOT
# plot(net_s15, layout = layout,
#      main = "Réseau d'interaction du site 15",
# )
```




#5. Kf
```{r}
colsums_s7 <- colSums(essence_presence_s7 == 1)
colsums_s14 <- colSums(essence_presence_s14 == 1)
colsums_s15 <- colSums(essence_presence_s15 == 1)
colsums_all <- colSums(essence_presence == 1)

kf_s7 <- data.frame(species = colnames(essence_presence_s7), s7 = colsums_s7, row.names = NULL)
kf_s14 <- data.frame(species = colnames(essence_presence_s14), s14 = colsums_s14, row.names = NULL)
kf_s15 <- data.frame(species = colnames(essence_presence_s15), s15 = colsums_s15, row.names = NULL)
kf_all <- data.frame(species = colnames(essence_presence), all = colsums_all, row.names = NULL)


kf_added_all <- kf_all %>%
  group_by(all) %>%
  summarize(count = n())

kf_added_all$all <- as.character(kf_added_all$all)

ggplot(kf_added_all, aes(x = all, y = count)) +
  geom_bar(stat = "identity", position = "dodge") +
  theme_minimal()

#S7
kf_added_s7 <- kf_s7 %>%
  group_by(s7) %>%
  summarize(count = n())
kf_added_s7$s7 <- as.character(kf_added_s7$s7)
ggplot(kf_added_s7, aes(x = s7, y = count)) +
  geom_bar(stat = "identity", position = "dodge") +
  theme_minimal()

#S14
kf_added_s14 <- kf_s14 %>%
  group_by(s14) %>%
  summarize(count = n())
kf_added_s14$s14 <- as.character(kf_added_s14$s14)
ggplot(kf_added_s14, aes(x = s14, y = count)) +
  geom_bar(stat = "identity", position = "dodge") +
  theme_minimal()

#S15
kf_added_s15 <- kf_s15 %>%
  group_by(s15) %>%
  summarize(count = n())
kf_added_s15$s15 <- as.character(kf_added_s15$s15)
ggplot(kf_added_s15, aes(x = s15, y = count)) +
  geom_bar(stat = "identity", position = "dodge") +
  theme_minimal()



```



#6. Kp
```{r}
row_sums <- rowSums(essence_presence == 1)
row_sums_s7 <- rowSums(essence_presence_s7 == 1)
row_sums_s14 <- rowSums(essence_presence_s14 == 1)
row_sums_s15 <- rowSums(essence_presence_s15 == 1)


kp_all <- data.frame(species = rownames(essence_presence), all = row_sums, row.names = NULL)
kp_s7 <- data.frame(species = rownames(essence_presence_s7), s7 = row_sums_s7, row.names = NULL)
kp_s14 <- data.frame(species = rownames(essence_presence_s14), s14 = row_sums_s14, row.names = NULL)
kp_s15 <- data.frame(species = rownames(essence_presence_s15), s15 = row_sums_s15, row.names = NULL)

kp <- kp_s7 %>%
  full_join(kp_s14, by = "species") %>%
  full_join(kp_s15, by = "species")

kp[is.na(kp)] <- 0


kp_long <- kp %>%
  pivot_longer(cols = c(s7, s14, s15), names_to = "Site", values_to = "Value")


apex_s7$s7 <- apex_s7$apex * 0.1
apex_s14$s14 <- apex_s14$apex * 0.1
apex_s15$s15 <- apex_s15$apex * 0.1

apex_s7$species <- row.names(apex_s7)
apex_s14$species <- row.names(apex_s14)
apex_s15$species <- row.names(apex_s15)

apex_all <- apex_s7 %>%
  full_join(apex_s14, by = "species") %>%
  full_join(apex_s15, by = "species")
  

apex_all_long <- apex_all %>%
  pivot_longer(cols = c("s7", "s14", "s15"),
               names_to = "Site",
               values_to = "coef")



kp_long <- kp_long %>%
  left_join(apex_all_long, by = c("Site", "species"))

kp_long$weighted <- kp_long$Value / kp_long$coef


kp_long$weighted[is.na(kp_long$weighted)] <- 0



ggplot(kp_long, aes(x = species, y = weighted, fill = Site)) +
  geom_bar(stat = "identity", position = "dodge") +  
  labs(x = "Species", y = "Count", title = "Nombre de degrés par espèce, pondéré pour 10 apex prélevés") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  

```

#7. Tests stats
```{r}
chi2_cast <- as.data.frame(weighted_double_pres[-c(3),])
chi2_cast$expected <- 1/8

obs <- chi2_cast$`Castanea sativa`
exp <- chi2_cast$expected

chisq.test(x=obs, p=exp)






count_family_chi_s7 <- invent_s7 %>%
  group_by(Famille) %>%
  summarize(s7_count =n())

count_family_chi_s14 <- invent_s14 %>%
  group_by(Famille) %>%
  summarize(s14_count =n())

count_family_chi_s15 <- invent_s15 %>%
  group_by(Famille) %>%
  summarize(s15_count =n())


count_family_chi_all <- count_family_chi_s7 %>%
  full_join(count_family_chi_s14, by = "Famille") %>%
  full_join(count_family_chi_s15, by = "Famille")

count_family_chi_all[is.na(count_family_chi_all)] <- 0

count_family_chi_all <- as.data.frame(count_family_chi_all)
row.names(count_family_chi_all) <- count_family_chi_all$Famille
count_family_chi_all$Famille <- NULL

chi_fam <- chisq.test(count_family_chi_all)
chi_fam$expected
chi_fam


count_family_chi_all_2 <- count_family_chi_all[!(count_family_chi_all$s7_count <= 1 & count_family_chi_all$s14_count <=1 & count_family_chi_all$s15_count <= 1),]


chi_fam_2 <- chisq.test(count_family_chi_all_2)
chi_fam_2$expected
chi_fam_2


```

